version: "3.9"

# Run terraform commands locally by executing them in a docker container running terraform
# e.g. docker-compose -f deploy/docker-compose.yml run --rm terraform validate

services:
  terraform:
    image: hashicorp/terraform:1.2.0
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
