version: "3.9"

services:
  terraform:
    image: hashicorp/terraform:1.2.0
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_NOPE}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_NOPE}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN_NOPE}
