name: Build, Test and Validate

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "GITHUB_SHA --> $GITHUB_SHA"
      - run: |
          cd app
          npm install
          npm run build
          npm run test:ci

  validate-terraform:
    name: 'Validate terraform'
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_SHA --> $GITHUB_SHA"
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: echo "sha short ---> ${{ steps.vars.outputs.sha_short }}"
