name: Build, Test and Validate

on:
  pull_request:
    branches:
      - master

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.step1.outputs.sha_short }}
    steps:
      - id: step1
        run: echo "::set-output name=sha_short::juukeli"

  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - uses: actions/checkout@v3
      - run: echo "GITHUB_SHA --> $GITHUB_SHA"
      - run: echo hmmmmm -----> ${{needs.set-vars.outputs.output1}}
      - run: echo ${{needs.set-vars.outputs.sha_short}}
      - run: |
          cd app
          npm install
          npm run build
          npm run test:ci

  validate-terraform:
    name: 'Validate terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8
      - run: echo "GITHUB_SHA --> $GITHUB_SHA"
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
