name: Build, Test and Validate

on:
  pull_request:
    branches:
      - master

env:
  TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}

jobs:
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm build && npm test
        run: |
          cd app
          npm install
          npm run build
          npm run test:ci
          npm run i:frontend
          npm run build:frontend

  validate-terraform:
    name: 'Validate terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0
      - name: Terraform validate
        run: |
          cd deploy
          terraform init -backend=false
          terraform validate
          terraform fmt -check
