name: Deploy to Staging

on:
  push:
    branches:
      - master
      - production

env:
  ECR_REPO: ${{ secrets.ECR_REPO }}

jobs:
  build-and-push:
    name: 'Docker Build and Push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add SHORT_SHA env
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Docker build, tag and push
        run: |
          cd app
          docker build --compress -t $ECR_REPO:$SHORT_SHA .
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 188405059934.dkr.ecr.eu-north-1.amazonaws.com
          docker push $ECR_REPO:$SHORT_SHA
          docker tag $ECR_REPO:$SHORT_SHA $ECR_REPO:latest
          docker push $ECR_REPO:latest

  staging-plan:
    name: 'Staging Plan'
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - run: echo "STAGING PLAN!!"

  staging-apply:
    name: 'Staging Apply'
    needs: [build-and-push, staging-plan]
    runs-on: ubuntu-latest
    steps:
      - run: echo "STAGING APPLY!!"
