name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: 'Docker Build and Push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "DOCKER BUILD AND PUSH!!!!"
