name: manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  log_something:
    name: 'Log something'
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello hello hello"
