name: pullrequest

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd app
          npm install
          npm run build
          npm run test:ci
