name: Deploy to Staging

on:
  push:
    branches:
      - master
      - production

jobs:
  build-and-push:
    name: 'Docker Build and Push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: |
          echo "Docker build and push with commit: ${{ steps.vars.outputs.sha_short }}"

  staging-plan:
    name: 'Staging Plan'
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - run: echo "STAGING PLAN!!"

  staging-apply:
    name: 'Staging Apply'
    needs: [build-and-push, staging-plan]
    runs-on: ubuntu-latest
    steps:
      - run: echo "STAGING APPLY!!"
