name: Destroy Staging

on:
  workflow_dispatch:

env:
  ECR_REPO: ${{ secrets.ECR_REPO }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-north-1

jobs:
  destroy-staging:
    name: "Destroy staging"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Destroy Staging
        run: |
          cd deploy
          terraform init
          terraform workspace select staging
          terraform destroy -auto-approve
